MIN_NRO_HANGAR=10
MAX_NRO_HANGAR=5000

MIN_OID_AVION=20552
MAX_OID_AVION=24510558

MIN_HANGARES = 1
MAX_HANGARES = 5

MIN_PRECIO_ESPACIO=3000
MAX_PRECIO_ESPACIO=100000
# Códigos de los materiales sacados de:
# https://en.wikipedia.org/wiki/Runway
COMPUESTOS = ['ASP', 'BIT', 'BRI', 'CLA', 'COM', 'CON', 'COP', 'COR', 'GRE', 'GVL', 'GRS', 'ICE', 'LAT', 'MAC', 'PEM', 'PER', 'PSP', 'SAN', 'SMT', 'SNO', 'U']
MIN_LONG        = 1000
MAX_LONG        = 5000
MIN_ANCHO       = 10
MAX_ANCHO       = 500
MIN_AEROLINEAS  = 10
MAX_AEROLINEAS  = 150
