version: '3'
services:
  alumnos:
    image: "postgres:9.6"
    container_name: "sitio-alumnos"
    volumes:
      - "$HOME/.local/universidad-volume/alumnos:/volume"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=universidad
      - PGDATA=/volume/data
    networks:
      universidad:
        ipv4_address: 172.20.0.10
  cursos:
    image: "postgres:9.6"
    container_name: "sitio-cursos"
    volumes:
      - "$HOME/.local/universidad-volume/cursos:/volume"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=universidad
      - PGDATA=/volume/data
    networks:
      universidad:
        ipv4_address: 172.20.0.20

networks:
  universidad:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 172.20.0.0/16 
